-- SQLite

DROP TABLE books;
DROP TABLE authors;
DROP TABLE customers;
DROP TABLE rents;


CREATE TABLE books (
	ID INTEGER PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	author INTEGER 
);

CREATE TABLE authors (
	ID INTEGER PRIMARY KEY,
	name VARCHAR(50) NOT NULL
);

CREATE TABLE customers (
	ID INTEGER PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(50) UNIQUE
);

CREATE TABLE rents (
	ID INTEGER PRIMARY KEY,
	bookID INTEGER REFERENCES books(ID),
	customerID INTEGER REFERENCES customers(ID),
	state VARCHAR(10) NOT NULL
);